import { Item } from "@/types/item";

// Helper to generate ISO dates relative to current time
const getPastDateISO = (daysAgo: number, hoursAgo = 0) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
};

export const INITIAL_ITEMS: Item[] = [
  {
    _id: "item_1",
    itemType: "lost",
    title: "Black Leather Coach Wallet",
    category: "Accessories",
    description: "Lost a black leather Coach bifold wallet. It contains my driver's license (initials J.D.), a gym membership card, and some cash. Lost near the central park jogging track.",
    location: "Central Park Jogging Track, New York",
    date: getPastDateISO(0, 3).split("T")[0], // 3 hours ago
    imageUrl: "https://images.unsplash.com/photo-1627124357773-41a19ab47f0f?w=600&auto=format&fit=crop&q=80",
    contactName: "John Doe",
    contactNumber: "555-0199",
    status: "active",
    postedBy: "user_demo_1",
    createdAt: getPastDateISO(0, 3),
    updatedAt: getPastDateISO(0, 3),
  },
  {
    _id: "item_2",
    itemType: "found",
    title: "iPhone 13 Pro - Silver/White",
    category: "Electronics",
    description: "Found an iPhone 13 Pro on the table at Starbucks. It has a blue silicone case and the battery is charged. Lock screen has a picture of a golden retriever. Please contact with proof of ownership (serial number or unlock passcode).",
    location: "Starbucks (5th Ave), New York",
    date: getPastDateISO(0, 5).split("T")[0], // 5 hours ago
    imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600&auto=format&fit=crop&q=80",
    contactName: "Sarah Connor",
    contactNumber: "555-0122",
    status: "active",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(0, 5),
    updatedAt: getPastDateISO(0, 5),
  },
  {
    _id: "item_3",
    itemType: "lost",
    title: "Golden Retriever Puppy - 'Max'",
    category: "Pet",
    description: "Our 6-month-old Golden Retriever puppy, Max, got scared by fireworks and ran out of the yard. He is wearing a red collar with a name tag. Very friendly but easily excited.",
    location: "Oakwood Heights Area, Brooklyn",
    date: getPastDateISO(1, 1).split("T")[0], // 1 day ago
    imageUrl: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80",
    contactName: "Michael Scott",
    contactNumber: "555-0177",
    status: "active",
    postedBy: "user_demo_1",
    createdAt: getPastDateISO(1, 1),
    updatedAt: getPastDateISO(1, 1),
  },
  {
    _id: "item_4",
    itemType: "found",
    title: "Car Key Fob (Honda)",
    category: "Keys",
    description: "Found a Honda key fob with a small leather keychain on the sidewalk outside the public library. Appears to be functional. Pressing the button lights up a small red LED.",
    location: "Public Library Main Entrance, New York",
    date: getPastDateISO(1, 6).split("T")[0], // 1.5 days ago
    imageUrl: "https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80",
    contactName: "Emily Watson",
    contactNumber: "555-0188",
    status: "active",
    postedBy: "user_demo_3",
    createdAt: getPastDateISO(1, 6),
    updatedAt: getPastDateISO(1, 6),
  },
  {
    _id: "item_5",
    itemType: "lost",
    title: "Grey Osprey Backpack",
    category: "Bag",
    description: "Left my grey Osprey commuter backpack on the northbound N Train during the evening rush hour. It contains a Lenovo ThinkPad laptop, a blue notebook, and Sennheiser noise-canceling headphones. Extremely critical for my work.",
    location: "N Train (Between Union Sq & Times Sq)",
    date: getPastDateISO(2).split("T")[0], // 2 days ago
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
    contactName: "David Miller",
    contactNumber: "555-0144",
    status: "active",
    postedBy: "user_demo_4",
    createdAt: getPastDateISO(2),
    updatedAt: getPastDateISO(2),
  },
  {
    _id: "item_6",
    itemType: "found",
    title: "US Passport - under the name 'Jessica R.'",
    category: "Documents",
    description: "Found a US Passport near the TSA pre-check line at JFK Airport Terminal 4. It belongs to Jessica R. I have handed it over to the airport police lost and found department, but posting here in case she checks online first.",
    location: "JFK Terminal 4 TSA Line, Queens",
    date: getPastDateISO(2, 4).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    contactName: "Robert Downey",
    contactNumber: "555-0155",
    status: "recovered",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(2, 4),
    updatedAt: getPastDateISO(1), // Updated 1 day ago when marked recovered
  },
  {
    _id: "item_7",
    itemType: "lost",
    title: "Brown Leather Jacket",
    category: "Clothing",
    description: "Forgot my vintage brown leather jacket on the back of a chair at the Red Lion Pub. It has a slight tear on the left elbow and contains a pair of black gloves in the right pocket.",
    location: "The Red Lion Pub (Bleecker St)",
    date: getPastDateISO(3).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80",
    contactName: "James Dean",
    contactNumber: "555-0111",
    status: "active",
    postedBy: "user_demo_1",
    createdAt: getPastDateISO(3),
    updatedAt: getPastDateISO(3),
  },
  {
    _id: "item_8",
    itemType: "found",
    title: "Ray-Ban Sunglasses - Black Aviator",
    category: "Accessories",
    description: "Found a pair of Ray-Ban Aviators with black lenses and gold rims sitting on a park bench. They are in a brown leather case. Good condition, no scratches.",
    location: "Madison Square Park, New York",
    date: getPastDateISO(4).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&auto=format&fit=crop&q=80",
    contactName: "Claire Temple",
    contactNumber: "555-0133",
    status: "active",
    postedBy: "user_demo_3",
    createdAt: getPastDateISO(4),
    updatedAt: getPastDateISO(4),
  },
  {
    _id: "item_9",
    itemType: "lost",
    title: "Kindle Paperwhite (11th Gen)",
    category: "Electronics",
    description: "Lost my Kindle Paperwhite in a green fabric cover. Last seen in the lobby seating area of the Marriott Hotel. It is registered under the name 'Amy' and displays a screen saver of a forest.",
    location: "Marriott Hotel Lobby, Times Square",
    date: getPastDateISO(5).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1496181130204-755241544e3f?w=600&auto=format&fit=crop&q=80",
    contactName: "Amy Pond",
    contactNumber: "555-0166",
    status: "active",
    postedBy: "user_demo_5",
    createdAt: getPastDateISO(5),
    updatedAt: getPastDateISO(5),
  },
  {
    _id: "item_10",
    itemType: "found",
    title: "Calico Cat with Pink Collar",
    category: "Pet",
    description: "A friendly calico cat has been hanging around my backyard for the last two days. It is wearing a pink collar with a bell, but no tag. Very vocal and loves wet food. Kept safe inside.",
    location: "Astoria, Queens",
    date: getPastDateISO(6).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    contactName: "Peter Parker",
    contactNumber: "555-0123",
    status: "active",
    postedBy: "user_demo_6",
    createdAt: getPastDateISO(6),
    updatedAt: getPastDateISO(6),
  },
  {
    _id: "item_11",
    itemType: "lost",
    title: "Student ID Card - NYU",
    category: "ID Card",
    description: "Lost my NYU Student Identification Card with the name 'Benjamin Parker' and student ID number ending in 849. Probably lost around the Washington Square Park campus or nearby subways.",
    location: "NYU Washington Square Campus, New York",
    date: getPastDateISO(7).split("T")[0],
    imageUrl: undefined,
    contactName: "Ben Parker",
    contactNumber: "555-0190",
    status: "active",
    postedBy: "user_demo_6",
    createdAt: getPastDateISO(7),
    updatedAt: getPastDateISO(7),
  },
  {
    _id: "item_12",
    itemType: "found",
    title: "Set of House Keys with Totoro Keychain",
    category: "Keys",
    description: "Found 4 keys on a brass ring, accompanied by a rubber Totoro figure keychain. Found lying on the grass near the children's playground.",
    location: "McCarren Park, Brooklyn",
    date: getPastDateISO(8).split("T")[0],
    imageUrl: undefined,
    contactName: "Jane Foster",
    contactNumber: "555-0112",
    status: "active",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(8),
    updatedAt: getPastDateISO(8),
  },
  {
    _id: "item_13",
    itemType: "lost",
    title: "Gold Engagement Ring",
    category: "Other",
    description: "Devastated to have lost my gold engagement ring. It has a single round diamond in a 4-prong setting. I took it off to wash my hands at the restaurant bathroom and left it on the sink edge.",
    location: "L'Artusi Restaurant Bathroom, West Village",
    date: getPastDateISO(10).split("T")[0],
    imageUrl: undefined,
    contactName: "Rachel Green",
    contactNumber: "555-0210",
    status: "recovered",
    postedBy: "user_demo_7",
    createdAt: getPastDateISO(10),
    updatedAt: getPastDateISO(5),
  },
  {
    _id: "item_14",
    itemType: "found",
    title: "Black FitBit Fitness Tracker",
    category: "Electronics",
    description: "Found a black Fitbit Charge tracker on the running path. It still has battery and screen turns on, but it is locked. Drop a line if you lost it.",
    location: "Hudson River Park Path, New York",
    date: getPastDateISO(11).split("T")[0],
    imageUrl: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop&q=80",
    contactName: "Tony Stark",
    contactNumber: "555-0100",
    status: "active",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(11),
    updatedAt: getPastDateISO(11),
  },
  {
    _id: "item_15",
    itemType: "lost",
    title: "Work Folder with Contract Documents",
    category: "Documents",
    description: "Lost a black plastic accordion-style folder containing multiple paper contracts and lease documents. It has a label saying 'Q3 Real Estate Group'. Extremely confidential. A reward will be given if returned intact.",
    location: "Grand Central Terminal Seating Area",
    date: getPastDateISO(12).split("T")[0],
    imageUrl: undefined,
    contactName: "Harvey Specter",
    contactNumber: "555-0077",
    status: "active",
    postedBy: "user_demo_8",
    createdAt: getPastDateISO(12),
    updatedAt: getPastDateISO(12),
  },
  {
    _id: "item_16",
    itemType: "found",
    title: "Blue Canvas Duffel Bag",
    category: "Bag",
    description: "Found a heavy blue canvas duffel bag left next to the benches. Contains gym clothes and running shoes. No ID cards inside, just basic gym gear.",
    location: "Prospect Park Tennis Courts, Brooklyn",
    date: getPastDateISO(14).split("T")[0],
    imageUrl: undefined,
    contactName: "Steve Rogers",
    contactNumber: "555-1941",
    status: "active",
    postedBy: "user_demo_3",
    createdAt: getPastDateISO(14),
    updatedAt: getPastDateISO(14),
  },
  {
    _id: "item_17",
    itemType: "lost",
    title: "Apple AirPods Pro Case",
    category: "Electronics",
    description: "Lost just the charging case for Apple AirPods Pro (1st generation). Left it in the library study room. The case has a custom engraving 'J.W.' on the front.",
    location: "Columbia University Butler Library Room 301",
    date: getPastDateISO(15).split("T")[0],
    imageUrl: undefined,
    contactName: "John Watson",
    contactNumber: "555-2212",
    status: "active",
    postedBy: "user_demo_9",
    createdAt: getPastDateISO(15),
    updatedAt: getPastDateISO(15),
  },
  {
    _id: "item_18",
    itemType: "found",
    title: "Designer Wool Scarf - Plaid/Beige",
    category: "Clothing",
    description: "Found a soft beige/plaid Burberry-style wool scarf draped over the fence. It is dry-clean only and in excellent condition. Left it with the park kiosk.",
    location: "High Line Park (near 23rd St access)",
    date: getPastDateISO(18).split("T")[0],
    imageUrl: undefined,
    contactName: "Donna Paulsen",
    contactNumber: "555-0078",
    status: "active",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(18),
    updatedAt: getPastDateISO(18),
  },
  {
    _id: "item_19",
    itemType: "lost",
    title: "Silver Helix Earring",
    category: "Accessories",
    description: "Lost a small silver helix earring shaped like a crescent moon with tiny inlaid blue stones. Probably dropped it while taking off my bike helmet.",
    location: "Williamsburg Bridge Bike Path, Brooklyn",
    date: getPastDateISO(20).split("T")[0],
    imageUrl: undefined,
    contactName: "Natasha Romanoff",
    contactNumber: "555-0909",
    status: "active",
    postedBy: "user_demo_10",
    createdAt: getPastDateISO(20),
    updatedAt: getPastDateISO(20),
  },
  {
    _id: "item_20",
    itemType: "found",
    title: "Driver's License (New York) - David K.",
    category: "ID Card",
    description: "Found a NY driver's license for a David K. on the floor of the subway car. I will mail it to the address listed on the license tomorrow if no one reaches out here first.",
    location: "L Train Subway (Brooklyn bound)",
    date: getPastDateISO(21).split("T")[0],
    imageUrl: undefined,
    contactName: "Bruce Banner",
    contactNumber: "555-0456",
    status: "recovered",
    postedBy: "user_demo_3",
    createdAt: getPastDateISO(21),
    updatedAt: getPastDateISO(20),
  },
  {
    _id: "item_21",
    itemType: "lost",
    title: "Black DJI Pocket 2 Camera",
    category: "Electronics",
    description: "Lost my DJI Pocket 2 gimbal camera while filming near the fountain. It was mounted on a small tripod. Contains family videos on a 128GB SanDisk microSD card. Please return it, the footage is precious.",
    location: "Bethesda Fountain, Central Park",
    date: getPastDateISO(22).split("T")[0],
    imageUrl: undefined,
    contactName: "Clark Kent",
    contactNumber: "555-0789",
    status: "active",
    postedBy: "user_demo_11",
    createdAt: getPastDateISO(22),
    updatedAt: getPastDateISO(22),
  },
  {
    _id: "item_22",
    itemType: "found",
    title: "Silver Mechanical Pencil (Pentel)",
    category: "Other",
    description: "Found a Pentel GraphGear 1000 drafting pencil lying on a desk. Good quality, heavy metallic grip. It has 0.5mm lead loaded.",
    location: "Cooper Union Engineering Building Room 402",
    date: getPastDateISO(25).split("T")[0],
    imageUrl: undefined,
    contactName: "Wanda Maximoff",
    contactNumber: "555-1024",
    status: "active",
    postedBy: "user_demo_2",
    createdAt: getPastDateISO(25),
    updatedAt: getPastDateISO(25),
  }
];
